version: '3.8'
services:
  db:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - network-retodz1
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    links:
      - "db:redis"
    networks:
      - network-retodz1

networks:
  network-retodz1:
    external: true