server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: reto1
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, beans, threaddump, mappings
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true
    beans:
      enabled: true
    threaddump:
      enabled: true
    mappings:
      enabled: true